version: '3.7'

services:
  mdc-app:
    volumes:
      - ./app/src:/src
    ports:
      - 8000:8000
      - 8888:8888

  mdc-db:
    ports:
      - 5432:5432

  mdc-ib:
    environment:
      - VNC_PASSWORD=$IB_VNC_PASSWORD
    ports:
      - 5900:5900
