version: '3.8'

services:
  dataserver-app:
    environment:
      - TZ=$TIME_ZONE
      - APP_DEBUG=$APP_DEBUG
      - APP_SECRET_KEY=$APP_SECRET_KEY
    container_name: dataserver-app
    restart: unless-stopped
    build: ./app
    depends_on:
      - dataserver-db

  dataserver-db:
    environment:
      - TZ=$TIME_ZONE
    container_name: dataserver-db
    image: mongo
    restart: unless-stopped
  
  dataserver-ib:
    environment:
      - TZ=$TIME_ZONE
      - IB_APP=$IB_APP
      - IB_MODE=$IB_MODE
      - IB_USER=$IB_USER
      - IB_PASSWORD=$IB_PASSWORD
    container_name: dataserver-ib
    image: zdytch/ib-dockerized
    restart: unless-stopped
